### ISSUE TITLE
Release the GPU memory after backward()

### ISSUE THREAD

**Issue by fleawood** [KevinMusgrave/pytorch-metric-learning#171]
I ran into a problem that faiss report an error during the evaluation phase:
```
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    main()
  File "train.py", line 141, in main
    trainer.train(num_epochs=num_epochs)
  File "/usr/local/lib/python3.7/site-packages/pytorch_metric_learning/trainers/base_trainer.py", line 90, in train
    if self.end_of_epoch_hook(self) is False:
  File "/usr/local/lib/python3.7/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 50, in actual_hook
    best_epoch = self.save_models_and_eval(trainer, dataset_dict, model_folder, test_interval, tester, test_collate_fn)
  File "/usr/local/lib/python3.7/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 93, in save_models_and_eval
    tester.test(dataset_dict, epoch, trainer.models["trunk"], trainer.models["embedder"], list(dataset_dict.keys()), collate_fn)
  File "/usr/local/lib/python3.7/site-packages/pytorch_metric_learning/testers/base_tester.py", line 221, in test
    self.do_knn_and_accuracies(self.all_accuracies[split_name], self.embeddings_and_labels, split_name)
  File "/usr/local/lib/python3.7/site-packages/pytorch_metric_learning/testers/global_embedding_space.py", line 21, in do_knn_and_accuracies
    self.embeddings_come_from_same_source(embeddings_and_labels),
  File "/usr/local/lib/python3.7/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py", line 130, in get_accuracy
    knn_indices, knn_distances = stat_utils.get_knn(reference, query, num_k, embeddings_come_from_same_source)
  File "/usr/local/lib/python3.7/site-packages/pytorch_metric_learning/utils/stat_utils.py", line 35, in get_knn
    index = faiss.index_cpu_to_all_gpus(index)
  File "/usr/local/lib/python3.7/site-packages/faiss/__init__.py", line 518, in index_cpu_to_all_gpus
    index_gpu = index_cpu_to_gpus_list(index, co=co, gpus=None, ngpu=ngpu)
  File "/usr/local/lib/python3.7/site-packages/faiss/__init__.py", line 530, in index_cpu_to_gpus_list
    index_gpu = index_cpu_to_gpu_multiple_py(res, index, co, gpus)
  File "/usr/local/lib/python3.7/site-packages/faiss/__init__.py", line 512, in index_cpu_to_gpu_multiple_py
    index = index_cpu_to_gpu_multiple(vres, vdev, index, co)
  File "/usr/local/lib/python3.7/site-packages/faiss/swigfaiss.py", line 5056, in index_cpu_to_gpu_multiple
    return _swigfaiss.index_cpu_to_gpu_multiple(resources, devices, index, options)
RuntimeError: Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:26: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 1610612736 bytes (error 2 out of memory)
```
This is strange because GPU memory is enough during training. 

I check the source code, and I find that `self.losses` do not released before `self.end_of_epoch_hook` is called.

https://github.com/KevinMusgrave/pytorch-metric-learning/blob/f1d8bf0901983503071cf9f0a053733b4218f0ae/src/pytorch_metric_learning/trainers/base_trainer.py#L78-L91

Pytorch will store computation graph if the losses are not released, so I suggest that call `zero_losses` at the end of the epoch, or use a detached loss value to record the results, and always release(delete) `self.losses` after backward().

**Comment by KevinMusgrave** [comment]
K I'll change it to this:
```python
            self.step_lr_schedulers(end_of_epoch=True)
            self.zero_losses() ##################### zero the loss dictionary at the end of the epoch
            if self.end_of_epoch_hook(self) is False:
                break
```

**Comment by KevinMusgrave** [comment]
This is in the latest version, v0.9.90. See the [release notes](https://github.com/KevinMusgrave/pytorch-metric-learning/releases/tag/v0.9.90) to see breaking changes and new features.
