### ISSUE TITLE
number of classes

### ISSUE THREAD

**Issue by jamesrobertwilliams** [KevinMusgrave/pytorch-metric-learning#218]
Is it possible to use the loss functions on multiple gpus?
I am trying something like this via torch.nn.DataParallel:

```
if torch.cuda.device_count() > 1:
        model = SomeModel(ini1)
        some_loss_func = losses.ArcFaceLoss(<classes>, <vec_len>, margin=<margin>, scale=<scale, weight_regularizer=<some_regulariser>)
        model_loss = ModelLoss(loss_func=some_loss_func) # this is part of the main model but a separate class which will be called by the main model to compute loss.
        model = torch.nn.DataParallel(model)
        model_loss = torch.nn.DataParallel(model_loss)
        model.to(device)
        model_loss.to(device)
```

but it seems to fail:

```
File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/snoopy/mario/pytorch_multigpu/etc/pytorch_multigpu/models.py", line 35, in forward
    loss = self.loss_func(pred, target)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/pytorch_metric_learning/losses/base_metric_loss_function.py", line 29, in forward
    loss_dict = self.compute_loss(embeddings, labels, indices_tuple)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/pytorch_metric_learning/losses/large_margin_softmax_loss.py", line 96, in compute_loss
    self.add_weight_regularization_to_loss_dict(loss_dict, self.W.t())
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/pytorch_metric_learning/losses/mixins.py", line 33, in add_weight_regularization_to_loss_dict
    loss_dict["weight_reg_loss"] = self.weight_regularization_loss(weights)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/pytorch_metric_learning/losses/mixins.py", line 28, in weight_regularization_loss
    loss = self.weight_regularizer(weights) * self.weight_reg_weight
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/pytorch_metric_learning/regularizers/base_regularizer.py", line 14, in forward
    loss_dict = self.compute_loss(x)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/pytorch_metric_learning/regularizers/regular_face_regularizer.py", line 15, in compute_loss
    cos = self.distance(weights)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/pytorch_metric_learning/distances/base_distance.py", line 24, in forward
    mat = self.compute_mat(query_emb_normalized, ref_emb_normalized)
  File "/home/snoopy/mario/pytorch_multigpu/lib/python3.7/site-packages/pytorch_metric_learning/distances/dot_product_similarity.py", line 10, in compute_mat
    return torch.matmul(query_emb, ref_emb.t())
RuntimeError: CUDA out of memory. Tried to allocate 18.72 GiB (GPU 0; 15.78 GiB total capacity; 575.26 MiB already allocated; 13.98 GiB free; 592.00 MiB reserved in total by PyTorch)
```

It somehow does not seem to parallelise the loss part of the code..

**Comment by KevinMusgrave** [comment]
Hi @jamesrobertwilliams I was able to run the following:

```python
import torch
from pytorch_metric_learning import losses, regularizers

device = torch.device('cuda')

weight_regularizer = regularizers.RegularFaceRegularizer()

loss_fn = losses.ArcFaceLoss(num_classes=10, embedding_size=512, weight_regularizer=weight_regularizer)
if torch.cuda.device_count() > 1:
    dataparallel_loss_fn = torch.nn.DataParallel(loss_fn)
    loss_fn.to(device)


embeddings = torch.randn(128, 512).to(device)
labels = torch.randint(low=0, high=10, size=(128,)).to(device)

print("loss_fn", loss_fn)
print("dataparallel_loss_fn", dataparallel_loss_fn)

loss = loss_fn(embeddings, labels)
print("loss", loss)

loss = dataparallel_loss_fn(embeddings, labels)
print("dataparallel loss", torch.mean(loss))
```

Could you provide more information about your setup? It says you're getting a cuda out of memory error. Are you sure that's caused by the loss function?

**Comment by jamesrobertwilliams** [comment]
Thank you for your snippet - yea, your code does work without any issue on `torch.nn.DataParallel`. Infact, without torch.nn.DataParallel, my code fails (out of memory), just because I have a large number of classes (50k). My embedding size is 512. When I have say 1k classes, everything works as expected! When I got this out of memory error, I starting looking into `torch.nn.DataParallel`, which I now realise was the wrong thing to do.

So, with everything else (setup) being the same:

```
### works
loss_fn = losses.ArcFaceLoss(num_classes=1000, embedding_size=512, weight_regularizer=weight_regularizer)
### does not work (out of memory)
loss_fn = losses.ArcFaceLoss(num_classes=1000, embedding_size=512, weight_regularizer=weight_regularizer)

batch_size=64.

```

How do I get around this problem :(

PS: I think it is better to rename the this `issue` as appropriate?

**Comment by KevinMusgrave** [comment]
Do you get the same memory error with ```torch.nn.CrossEntropyLoss```?

If so, you could try lowering the embedding size (by adding an extra layer to your network which goes from 512 to 128 for example).

Alternatively, you could look into [DistributedDataParallel](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html), assuming that you have multiple gpus, and assuming that a batch size of 1 doesn't currently give you a memory error.

**Comment by jamesrobertwilliams** [comment]
I have not tried crossentropy loss, but I can try lowering the embedding dimension and report back on this.

The funny thing is, I get exactly the same out of memory error on multiple gpus aswell. My distributed code (using ddp as you suggest via lightning) again, runs in a distributed manner (all 4 16gb gpus see equal load) when I use say 1k classes, but runs out of memory on 50k classes. A bit surprising why it would do so - maybe some part of the loss is not able to be parallelised?

**Comment by KevinMusgrave** [comment]
As a sanity check, try using cross entropy loss and see if you get the same problem. I guess you'll need to append a layer to your network that goes from 512 to 50000, and then feed that to the loss function.

**Comment by jamesrobertwilliams** [comment]
@KevinMusgrave OK let me try the CEL and come back.
Meanwile, I did a few quick tests on a single 4gb gpu, with setup the same:

```
##38k classes:
RuntimeError: CUDA out of memory. Tried to allocate 5.38 GiB (GPU 0; 2.95 GiB total capacity; 49.44 MiB already allocated; 1.91 GiB free; 70.00 MiB reserved in total by PyTorch)
## 40k classes
RuntimeError: CUDA out of memory. Tried to allocate 5.96 GiB (GPU 0; 2.95 GiB total capacity; 49.90 MiB already allocated; 1.91 GiB free; 70.00 MiB reserved in total by PyTorch)
## 50k classes
RuntimeError: CUDA out of memory. Tried to allocate 9.31 GiB (GPU 0; 2.95 GiB total capacity; 53.16 MiB already allocated; 1.91 GiB free; 70.00 MiB reserved in total by PyTorch)
```

**Comment by jamesrobertwilliams** [comment]
@KevinMusgrave I made this other check now:

```
import torch
from pytorch_metric_learning import losses, regularizers

device = torch.device('cuda')
weight_regularizer = regularizers.RegularFaceRegularizer()
loss_fn = losses.ArcFaceLoss(num_classes=5000, embedding_size=512, weight_regularizer=weight_regularizer)
loss_fn.to(device)
embeddings = torch.randn(128, 512).to(device)
labels = torch.randint(low=0, high=10, size=(128,)).to(device)

loss = loss_fn(embeddings, labels)
print(loss)

Out: tensor(43.3781, device='cuda:0', grad_fn=<SumBackward0>)

```

Now, I just increase the number of classes to 10k:

```
import torch
from pytorch_metric_learning import losses, regularizers

device = torch.device('cuda')
weight_regularizer = regularizers.RegularFaceRegularizer()
loss_fn = losses.ArcFaceLoss(num_classes=10000, embedding_size=512, weight_regularizer=weight_regularizer)
loss_fn.to(device)
embeddings = torch.randn(128, 512).to(device)
labels = torch.randint(low=0, high=10, size=(128,)).to(device)

loss = loss_fn(embeddings, labels)
print(loss)

Out: RuntimeError: CUDA out of memory. Tried to allocate 382.00 MiB (GPU 0; 2.95 GiB total capacity; 463.41 MiB already allocated; 368.19 MiB free; 484.00 MiB reserved in total by PyTorch)
```

Is my approach here wrong? I think this is exactly my error (the stacktrace is exactly the same as posted before):

```
    loss = loss_fn(embeddings, labels)
  File "/home/snoopy/mario/pytorch_runs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/snoopy/mario/pytorch_runs/lib/python3.7/site-packages/pytorch_metric_learning/losses/base_metric_loss_function.py", line 29, in forward
    loss_dict = self.compute_loss(embeddings, labels, indices_tuple)
  File "/home/snoopy/mario/pytorch_runs/lib/python3.7/site-packages/pytorch_metric_learning/losses/large_margin_softmax_loss.py", line 96, in compute_loss
    self.add_weight_regularization_to_loss_dict(loss_dict, self.W.t())
  File "/home/snoopy/mario/pytorch_runs/lib/python3.7/site-packages/pytorch_metric_learning/losses/mixins.py", line 33, in add_weight_regularization_to_loss_dict
    loss_dict["weight_reg_loss"] = self.weight_regularization_loss(weights)
  File "/home/snoopy/mario/pytorch_runs/lib/python3.7/site-packages/pytorch_metric_learning/losses/mixins.py", line 28, in weight_regularization_loss
    loss = self.weight_regularizer(weights) * self.weight_reg_weight
  File "/home/snoopy/mario/pytorch_runs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/snoopy/mario/pytorch_runs/lib/python3.7/site-packages/pytorch_metric_learning/regularizers/base_regularizer.py", line 14, in forward
    loss_dict = self.compute_loss(x)
  File "/home/snoopy/mario/pytorch_runs/lib/python3.7/site-packages/pytorch_metric_learning/regularizers/regular_face_regularizer.py", line 16, in compute_loss
    cos1 = cos.clone()
RuntimeError: CUDA out of memory. Tried to allocate 382.00 MiB (GPU 0; 2.95 GiB total capacity; 463.41 MiB already allocated; 368.19 MiB free; 484.00 MiB reserved in total by PyTorch)
```

**Comment by KevinMusgrave** [comment]
In this case, RegularFaceRegularizer requires a lot of memory because it does a matrix multiplication of (50000, 512) * (512, 50000).

I was suggesting trying CEL just to make sure the memory issues isn't caused by pytorch-metric-learning.

Anyway, during training, having a huge output layer will require a lot of gradient computation which increases the memory requirement. You could also look into checkpointing: https://pytorch.org/docs/stable/checkpoint.html

**Comment by jamesrobertwilliams** [comment]
@KevinMusgrave Yes, it is what you said. I turned off the RegularFaceRegularizer and it starts to train! 
I will check out the other regularisers.
