### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'fill_diagonal_'

### ISSUE THREAD

**Issue by QinZiwen** [KevinMusgrave/pytorch-metric-learning#220]
When run "https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/examples/notebooks/TripletMarginLossMNIST.ipynb", it has some errors:
```
Traceback (most recent call last):
  File "TripletMarginLossMNIST.py", line 93, in <module>
    train(model, loss_func, mining_func, device, train_loader, optimizer, epoch)
  File "TripletMarginLossMNIST.py", line 40, in train
    indices_tuple = mining_func(embeddings, labels)
  File "python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "python3.6/site-packages/pytorch_metric_learning/miners/base_miner.py", line 28, in forward
    mining_output = self.mine(embeddings, labels, ref_emb, ref_labels)
  File "python3.6/site-packages/pytorch_metric_learning/miners/triplet_margin_miner.py", line 30, in mine
    labels, ref_labels
  File "python3.6/site-packages/pytorch_metric_learning/utils/loss_and_miner_utils.py", line 87, in get_all_triplets_indices
    matches.fill_diagonal_(0)
AttributeError: 'Tensor' object has no attribute 'fill_diagonal_'


```

**Comment by KevinMusgrave** [comment]
It is a valid function: https://pytorch.org/docs/stable/tensors.html#torch.Tensor.fill_diagonal_

You may need to upgrade your version of pytorch.

**Comment by QinZiwen** [comment]
thanks
