### ISSUE TITLE
Deterministic bahavior for losses

### ISSUE THREAD

**Issue by Apich238** [KevinMusgrave/pytorch-metric-learning#382]
The following example of code works fine if torch.set_deterministic(False) and raise exception if torch.set_deterministic(True):

```
import os
import torch
import torch.nn.functional as F
from pytorch_metric_learning.losses import ArcFaceLoss
from torch import nn

os.environ["CUBLAS_WORKSPACE_CONFIG"] = ':4096:8'
print('pytorch threads ', torch.get_num_threads())
print('version', torch.version.__version__)

torch.set_deterministic(True)

dev = torch.device('cuda')

n_classes=1000
ndim=512
batchsz=256

model = nn.Embedding(n_classes, ndim).to(dev)
labels = torch.randint(high=n_classes, size=(batchsz,)).to(dev)  # our five labels

L=ArcFaceLoss(num_classes=n_classes, embedding_size=ndim, margin=28.6, scale=64)

embeddings = F.normalize(model(labels))
print('Labels:', labels.cpu())
print('Embeddings:', embeddings.cpu())
loss = L(labels=labels, embeddings=embeddings)
loss.backward()
print('Loss:', loss.cpu())
```
code output:

```
pytorch threads  6
version 1.9.0+cu111
/home/alex/.local/lib/python3.6/site-packages/torch/__init__.py:472: UserWarning: torch.set_deterministic is deprecated and will be removed in a future release. Please use torch.use_deterministic_algorithms instead
  "torch.set_deterministic is deprecated and will be removed in a future "
Labels: tensor([800, 504, 405, 824, 157, 173, 709, 949, 763, 424, 696,  31, 943, 511,
        332, 361, 655, 972, 778, 946, 722, 637, 590, 616, 361, 570, 728, 619,
         75, 525, 872, 956, 499, 538, 736, 505, 893, 582, 361, 876, 758,   3,
         45, 849, 499, 185, 746, 315, 626, 933, 143, 205, 551, 964, 527, 843,
        615, 569, 855, 721, 261, 472,  93, 897, 427, 239, 677, 858,  54, 957,
        143, 630, 824, 475,  89,   9, 193, 539, 909, 104,  12, 988, 162, 839,
        528, 934, 552, 183, 821, 344, 199, 526, 111, 504, 591, 892, 355,  18,
        677, 309, 821, 725, 425, 435,  58, 448, 643, 459, 243, 330, 597, 139,
        284, 745, 814,  28, 852, 901,  67, 168,  42, 984, 104, 695, 318,  11,
        628, 630, 268, 691,  43, 294, 449, 873, 903,  52, 124, 713, 854, 969,
        790, 702, 406, 393, 145,  56, 474,  63, 856, 279, 303, 950, 127, 952,
         85, 375, 493, 546, 291, 655, 466, 695, 733, 863, 804, 180, 254, 606,
        741, 172, 889,  65, 635, 336, 536, 330, 607, 351,  74,  84, 483, 718,
         82, 187, 502, 266, 256, 257, 286,  22, 303, 931, 522, 451, 988, 917,
        454, 598, 237, 611, 837, 763,  27, 875, 256, 445, 733, 259,  12,  27,
        332, 473, 132,  92, 623, 187, 566, 175, 887, 122, 708, 954, 867, 455,
         16, 371, 124, 390, 853, 771, 588, 354, 119, 582, 745, 360, 719, 884,
        797, 835, 774, 994, 888, 961,  10, 517, 912, 342, 805, 219, 515, 995,
        166,  90,  40, 597])
Embeddings: tensor([[ 0.0213, -0.0178,  0.0034,  ..., -0.0193, -0.0087,  0.0503],
        [-0.0839, -0.0488,  0.0528,  ..., -0.0004,  0.0630, -0.0185],
        [-0.0101, -0.0805,  0.0265,  ...,  0.0301, -0.0147,  0.0549],
        ...,
        [ 0.0071,  0.0329,  0.0639,  ...,  0.0145,  0.0200,  0.0554],
        [-0.0744,  0.0068, -0.0369,  ..., -0.0237,  0.0431, -0.0794],
        [-0.0057, -0.0917, -0.0588,  ..., -0.0283,  0.0114, -0.0472]],
       grad_fn=<CopyBackwards>)
Traceback (most recent call last):
  File "/snap/pycharm-community/256/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/256/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/sdb/faces/facerec/outdated/baga.py", line 28, in <module>
    loss = L(labels=labels, embeddings=embeddings)
  File "/home/alex/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/alex/.local/lib/python3.6/site-packages/pytorch_metric_learning/losses/base_metric_loss_function.py", line 34, in forward
    loss_dict = self.compute_loss(embeddings, labels, indices_tuple)
  File "/home/alex/.local/lib/python3.6/site-packages/pytorch_metric_learning/losses/large_margin_softmax_loss.py", line 105, in compute_loss
    mask = self.get_target_mask(embeddings, labels)
  File "/home/alex/.local/lib/python3.6/site-packages/pytorch_metric_learning/losses/large_margin_softmax_loss.py", line 74, in get_target_mask
    mask[torch.arange(batch_size), labels] = 1
RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == value.numel()INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cuda/Indexing.cu":253, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor2561
```

**Comment by Apich238** [comment]
I didn't tested but I expect this bug exist in other loss functions too

**Comment by KevinMusgrave** [comment]
No idea what causes that. This issue may be related: https://github.com/pytorch/pytorch/issues/66710

**Comment by Apich238** [comment]
After installing pytorch 1.10 and replacing torch.set_deterministic(True) with torch.use_deterministic_algorithms(True) error is same:
```
...
  File "/home/alex/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/alex/.local/lib/python3.6/site-packages/pytorch_metric_learning/losses/base_metric_loss_function.py", line 34, in forward
    loss_dict = self.compute_loss(embeddings, labels, indices_tuple)
  File "/home/alex/.local/lib/python3.6/site-packages/pytorch_metric_learning/losses/large_margin_softmax_loss.py", line 105, in compute_loss
    mask = self.get_target_mask(embeddings, labels)
  File "/home/alex/.local/lib/python3.6/site-packages/pytorch_metric_learning/losses/large_margin_softmax_loss.py", line 74, in get_target_mask
    mask[torch.arange(batch_size), labels] = 1
RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == value.numel()INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cuda/Indexing.cu":250, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor2561
```

**Comment by KevinMusgrave** [comment]
Hmm, actually someone has the same problem now in v1.10: https://github.com/pytorch/pytorch/issues/68525

**Comment by KevinMusgrave** [comment]
It looks like it's been fixed: https://github.com/pytorch/pytorch/issues/68525#issuecomment-973429568

**Comment by KevinMusgrave** [comment]
Closing this because it seems to be a pytorch issue rather than a PML issue

**Comment by isahumbaiev** [comment]
Still having this issue in the code `(large_margin_softmax.py)`
```
    def get_target_mask(self, embeddings, labels):
        batch_size = labels.size(0)
        mask = torch.zeros(
            batch_size,
            self.num_classes,
            dtype=embeddings.dtype,
            device=embeddings.device,
        )
        --> mask[torch.arange(batch_size), labels] = 1
        return mask
```

but if I  change

```
mask[torch.arange(batch_size), labels] = torch.ones(batch_size, device=embeddings.device)
```
error disappears.
