### ISSUE TITLE
Tensors missmatch in inference model

### ISSUE THREAD

**Issue by shaikaz** [KevinMusgrave/pytorch-metric-learning#403]
Hi, I run into two issues:

1. If I'm running: 
`inference_model.train_knn(dataset, batch_size=bs)`
where `bs != 1` I'm getting: 
`RuntimeError: stack expects each tensor to be equal size, but got [3, 64, 145] at entry 0 and [3, 65, 64] at entry 1`
But when `bs=1`,it's OK (64 is my embedding dim)

2. When I'm running
`indices, distances = inference_model.get_nearest_neighbors(img, k=3)`
I'm getting:
`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 3-dimensional input of size [3, 64, 85] instead`

Does anyone got into these issues?

Thanks!
Shai

**Comment by KevinMusgrave** [comment]
Can you provide the full stack trace?

**Comment by shaikaz** [comment]
Sure!

For 1:
`Traceback (most recent call last):
  File "/Users/shaikazaz/Desktop/gen_metric/infer.py", line 173, in <module>
    inference_model.train_knn(dataset, batch_size=2)
  File "/usr/local/lib/python3.9/site-packages/pytorch_metric_learning/utils/inference.py", line 99, in train_knn
    self.call_knn(self.knn_func.train, inputs, batch_size)
  File "/usr/local/lib/python3.9/site-packages/pytorch_metric_learning/utils/inference.py", line 105, in call_knn
    embeddings = self.get_embeddings_from_tensor_or_dataset(inputs, batch_size)
  File "/usr/local/lib/python3.9/site-packages/pytorch_metric_learning/utils/inference.py", line 92, in get_embeddings_from_tensor_or_dataset
    for inp, _ in dataloader:
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 64, 145] at entry 0 and [3, 65, 64] at entry 1`

For 2:
`Traceback (most recent call last):
  File "/Users/shaikazaz/Desktop/gen_metric/infer.py", line 178, in <module>
    indices, distances = inference_model.get_nearest_neighbors(img, k=3)
  File "/usr/local/lib/python3.9/site-packages/pytorch_metric_learning/utils/inference.py", line 109, in get_nearest_neighbors
    query_emb = self.get_embeddings(query)
  File "/usr/local/lib/python3.9/site-packages/pytorch_metric_learning/utils/inference.py", line 119, in get_embeddings
    x_emb = self.embedder(self.trunk(x))
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/torchvision/models/resnet.py", line 249, in forward
    return self._forward_impl(x)
  File "/usr/local/lib/python3.9/site-packages/torchvision/models/resnet.py", line 232, in _forward_impl
    x = self.conv1(x)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 3-dimensional input of size [3, 64, 85] instead`

**Comment by KevinMusgrave** [comment]
Error 1 is coming from the pytorch dataloader. I think your dataset elements are of different sizes, so it's unable to stack them.

Error 2 seems to indicate that the data is the wrong size for the model. As a sanity check, you can try doing ```model(img)``` and see if you get the same error.

**Comment by shaikaz** [comment]
As for 2:
I'm getting the same error when I'm doing it as you said:

 `Traceback (most recent call last):
  File "/Users/shaikazaz/Desktop/gen_metric/infer.py", line 177, in <module>
    e = embbeder(trunk(img_))
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/torchvision/models/resnet.py", line 249, in forward
    return self._forward_impl(x)
  File "/usr/local/lib/python3.9/site-packages/torchvision/models/resnet.py", line 232, in _forward_impl
    x = self.conv1(x)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 3-dimensional input of size [3, 64, 64] instead`

I what to say that I'm sure I'm using the image transformation as I should be

Thanks!

**Comment by KevinMusgrave** [comment]
If it's a single image (batch size = 1), try doing ```img_ = img_.unsqueeze(0)```

**Comment by shaikaz** [comment]
As for 2 it's solved the issue, Thanks. 
As for 1, I'm still looking at it, I'm using the same dataloader I use in the training phase which worked fine.
