### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

### ISSUE THREAD

**Issue by TEnsorTHiru** [KevinMusgrave/pytorch-metric-learning#530]
I have checked the dataset and cleaned it, there are no problems with the dataset. But I keep getting this error when I start training after two or three epochs, Is there a way to identify or find where this issue arises.

**ERROR LOG:**

Traceback (most recent call last):
  File "train_met.py", line 154, in <module>
    trainer.train(num_epochs=num_epochs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_metric_learning/trainers/base_trainer.py", line 93, in train
    if self.end_of_epoch_hook(self) is False:
  File "/opt/conda/lib/python3.7/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 97, in actual_hook
    test_collate_fn,
  File "/opt/conda/lib/python3.7/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 171, in save_models_and_eval
    collate_fn,
  File "/opt/conda/lib/python3.7/site-packages/pytorch_metric_learning/testers/base_tester.py", line 298, in test
    self.maybe_visualize(self.embeddings_and_labels, epoch)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_metric_learning/testers/base_tester.py", line 146, in maybe_visualize
    dim_reduced = self.visualizer.fit_transform(embeddings.cpu().numpy())
  File "/opt/conda/lib/python3.7/site-packages/umap/umap_.py", line 2772, in fit_transform
    self.fit(X, y)
  File "/opt/conda/lib/python3.7/site-packages/umap/umap_.py", line 2269, in fit
    X = check_array(X, dtype=np.float32, accept_sparse="csr", order="C")
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

**Comment by KevinMusgrave** [comment]
Usually this happens if your learning rate is too high.

**Comment by TEnsorTHiru** [comment]
I have set the learning rate to default 0.01

**Comment by KevinMusgrave** [comment]
That could be too high. Here are some related threads:

https://discuss.pytorch.org/t/why-my-model-returns-nan/24329
https://discuss.pytorch.org/t/output-of-model-is-nan-every-time/89114
https://discuss.pytorch.org/t/model-returning-nan-as-output/82510

**Comment by TEnsorTHiru** [comment]
> That could be too high. Here are some related threads:
> 
> https://discuss.pytorch.org/t/why-my-model-returns-nan/24329 https://discuss.pytorch.org/t/output-of-model-is-nan-every-time/89114 https://discuss.pytorch.org/t/model-returning-nan-as-output/82510

I tried everything in these threads but still the problem didn't get solved

**Comment by KevinMusgrave** [comment]
Hmm, I'm not sure what else it could be. What loss function, miner, distance etc. are you using?

**Comment by TEnsorTHiru** [comment]
I have attached the entire training script here.
Loss Function: ArcFace Loss - default setting.
Batch size: 16
Optimizer = Adam
LR = 0.001
No Miners


```

import logging

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torchvision
import umap
from cycler import cycler
from PIL import Image
from torchvision import datasets, transforms
import toml
from models.efficientv1 import load_model, Embedder
from utils.clfr_dataset import ClassifierDataset
import pytorch_metric_learning
import pytorch_metric_learning.utils.logging_presets as logging_presets
from pytorch_metric_learning import losses, miners, samplers, testers, trainers
from pytorch_metric_learning.utils import common_functions
from pytorch_metric_learning.utils.accuracy_calculator import AccuracyCalculator
import torchvision

logging.getLogger().setLevel(logging.INFO)
logging.info("VERSION %s" % pytorch_metric_learning.__version__)


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

log = open("embedd.txt","w")


class HappyTrainer(trainers.MetricLossOnly):
    def __init__(self, *args, accumulation_steps=10, **kwargs):
        super().__init__(*args, **kwargs)
        self.accumulation_steps = accumulation_steps

    def forward_and_backward(self):
        self.zero_losses()
        self.update_loss_weights()
        self.calculate_loss(self.get_batch())
        self.loss_tracker.update(self.loss_weights)
        self.backward()
        self.clip_gradients()
        if ((self.iteration + 1) % self.accumulation_steps == 0) or ((self.iteration + 1) == np.ceil(len(self.dataset) / self.batch_size)):
            self.step_optimizers()
            self.zero_grad()
            
    def calculate_loss(self, curr_batch):
        data, labels = curr_batch
        with torch.cuda.amp.autocast():
            embeddings = self.compute_embeddings(data)
            # embeddings = torch.nan_to_num(embeddings)
            log.write(f"{embeddings.min()} {embeddings.max()}\n")
            indices_tuple = self.maybe_mine_embeddings(embeddings, labels)
            self.losses["metric_loss"] = self.maybe_get_metric_loss(
                embeddings, labels, indices_tuple
            )


def visualizer_hook(umapper, umap_embeddings, labels, split_name, keyname, *args):
    logging.info(
        "UMAP plot for the {} split and label set {}".format(split_name, keyname)
    )
    label_set = np.unique(labels)
    num_classes = len(label_set)
    plt.figure(figsize=(20, 15))
    plt.gca().set_prop_cycle(
        cycler(
            "color", [plt.cm.nipy_spectral(i) for i in np.linspace(0, 0.9, num_classes)]
        )
    )
    for i in range(num_classes):
        idx = labels == label_set[i]
        plt.plot(umap_embeddings[idx, 0], umap_embeddings[idx, 1], ".", markersize=1)
    plt.show()
    plt.savefig(f"classifier_logs/{split_name}.png")

if __name__ == "__main__":
    configs = toml.load("config.toml")
    
    for f in range(1,5):

        #Dataset Creation Fold-wise
        train_dataset = ClassifierDataset("resized", 512, f, "train")
        val_dataset = ClassifierDataset("resized", 512, f, "validation")
        
        #Trunk Model Creation
        # trunk = load_model(configs['backbone']['name'], configs['head']['num_classes'])
        trunk = torchvision.models.resnet18(pretrained=True)
        trunk_output_size = trunk.fc.in_features
        trunk.fc = common_functions.Identity()
        trunk = torch.nn.DataParallel(trunk.to(device))

        #Embedder Model Creation
        embedder = torch.nn.DataParallel(Embedder([trunk_output_size, 100], True).to(device))


        #Classifier Model Creation
        # classifier = torch.nn.DataParallel(Embedder([100, configs['head']['num_classes']]).to(device))


        #Optimizers
        trunk_optimizer = torch.optim.Adam(trunk.parameters(), lr=0.001)
        embedder_optimizer = torch.optim.Adam(embedder.parameters(), lr=0.001)
        # classifier_optimizer = torch.optim.Adam(classifier.parameters(), lr=0.01, weight_decay=0.0001)
        
        

        metric_loss = losses.ArcFaceLoss(num_classes=configs["head"]["num_classes"], embedding_size=100)
        metric_loss_optimizer = torch.optim.Adam(metric_loss.parameters(), lr=0.001)
        # classifier_loss = nn.CrossEntropyLoss()

        
        batch_size = 16
        num_epochs = 50

        models = {"trunk":trunk, "embedder":embedder}

        optimizers = {
            "trunk_optimizer":trunk_optimizer,
            "embedder_optimizer":embedder_optimizer,
            "metric_loss_optimizer":metric_loss_optimizer
        }

        loss_funcs = {"metric_loss":metric_loss}
        # loss_weights = {"metric_loss":1, "classifier_loss":0.5}
    

        record_keeper, _, _ = logging_presets.get_record_keeper("classifier_logs", "classifier_tensorboard")
        hooks = logging_presets.get_hook_container(record_keeper=record_keeper)
        dataset_dict = {"val":val_dataset}
        model_folder = "metric_learning"

        tester = testers.GlobalEmbeddingSpaceTester(
            end_of_testing_hook=hooks.end_of_testing_hook,
            visualizer=umap.UMAP(),
            visualizer_hook=visualizer_hook,
            dataloader_num_workers=4,
            accuracy_calculator=AccuracyCalculator(k="max_bin_count")

        )

        end_of_epoch_hook = hooks.end_of_epoch_hook(tester, dataset_dict, model_folder, 1,patience=7)


        trainer = trainers.TrainWithClassifier(
            models,
            optimizers,
            batch_size,
            loss_funcs,
            mining_funcs={},
            dataset=train_dataset,
            dataloader_num_workers=4,
            end_of_iteration_hook=hooks.end_of_iteration_hook,
            end_of_epoch_hook=end_of_epoch_hook
        )


        trainer.train(num_epochs=num_epochs)

```

**Comment by TEnsorTHiru** [comment]
The Loss keeps on going too low and at the end, it goes to NaN. The accuracy always stays at 0.04%
[classifier_logs.zip](https://github.com/KevinMusgrave/pytorch-metric-learning/files/9658350/classifier_logs.zip)

**Comment by TEnsorTHiru** [comment]
@KevinMusgrave  I have also attached classifier_logs here.

**Comment by KevinMusgrave** [comment]
Two possibly related issues:

- [ArcFaceLoss parameters become nan after several epochs](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/209)
- [Poor performance of ArcFace loss compared to CrossEntropy](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/351)

**Comment by TEnsorTHiru** [comment]
I'm trying this both, have rescaled it to 8 and changed to SGD with momentum from Adam.

**Comment by TEnsorTHiru** [comment]
> Two possibly related issues:
> 
>     * [ArcFaceLoss parameters become nan after several epochs](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/209)
> 
>     * [Poor performance of ArcFace loss compared to CrossEntropy](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/351)

Actually this fixed my problem. Thanks for your help, I rescaled the scale to 8 and used sgd with momentum instead of adam. The training is going good with 90mAP.
