### ISSUE TITLE
NT-Xent loss causing CUDA OOM: trying to allocate 120GB memory 

### ISSUE THREAD

**Issue by siddagra** [KevinMusgrave/pytorch-metric-learning#547]
Error caused when

```py
        a = conProj.flatten(start_dim=0,end_dim=1)
        b = torch.tensor(tgt_out).flatten()
        
        print(a.shape, b.shape)
        conLoss = self.conLoss(a, b)
```
```
//print output
torch.Size([1200, 192])   torch.Size([1200])
```

I am not sure why it is taking so much memory since it is only an exp(inner product of two vectors). any good way to avoid this?

Error:
```
Traceback (most recent call last):
  File "/media/siddharth/7200rpm Seagate/UGRP-TruckNumberPlate/parseq_contrastive/train.py", line 95, in main
    trainer.fit(model, datamodule=datamodule)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 266, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 203, in advance
    result = self._run_optimization(
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 369, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1646, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 85, in optimizer_step
    closure_result = closure()
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 134, in closure
    step_output = self._step_fn()
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 427, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *step_kwargs.values())
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 333, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/media/siddharth/7200rpm Seagate/UGRP-TruckNumberPlate/parseq_contrastive/strhub/models/parseq/system.py", line 266, in training_step
    conLoss = self.conLoss(conProj.flatten(start_dim=0,end_dim=1), torch.tensor(tgt_out).flatten())
  File "/home/siddharth/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_metric_learning/losses/base_metric_loss_function.py", line 38, in forward
    loss_dict = self.compute_loss(
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_metric_learning/losses/generic_pair_loss.py", line 20, in compute_loss
    return self.loss_method(mat, indices_tuple)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_metric_learning/losses/generic_pair_loss.py", line 39, in pair_based_loss
    return self._compute_loss(pos_pair, neg_pair, indices_tuple)
  File "/home/siddharth/.local/lib/python3.9/site-packages/pytorch_metric_learning/losses/ntxent_loss.py", line 26, in _compute_loss
    n_per_p = c_f.to_dtype(a2.unsqueeze(0) == a1.unsqueeze(1), dtype=dtype)
RuntimeError: CUDA out of memory. Tried to allocate 120.13 GiB (GPU 0; 9.78 GiB total capacity; 836.91 MiB already allocated; 6.24 GiB free; 850.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

I am not sure why it is taking so much memory since it is only an exp(inner product of two vectors). any good way to avoid this?

**Comment by siddagra** [comment]
If providing indices help, please tell me how I should go about finding positive and negative pairs in this array as it is unsorted and I have no way of getting positive/negative indices beforehand.

**Comment by KevinMusgrave** [comment]
You could try creating indices using a miner, but the miner will probably also run out of memory.

```python
from pytorch_metric_learning.miners import MultiSimilarityMiner

miner = MultiSimilarityMiner()
pairs = miner(a, b)
loss = loss_fn(a, indices_tuple=pairs)
```

Another approach is to loop through the batch. To maintain the same number of total pairs, you can use `ref_emb` to hold the full batch. In the example below, `curr_anchors` will have 32 embeddings and will be the source of the "anchors". The `ref_emb` will contain the full 1200 embeddings and will be the source for positives and negatives.

```python
import torch
from pytorch_metric_learning import losses, reducers
from pytorch_metric_learning.utils import loss_and_miner_utils as lmu


# setup
device = torch.device("cuda")
batch_size = 1200
a = torch.randn(batch_size, 32, device=device)
b = torch.randint(0, 10, size=(batch_size,), device=device)

# The regular approach runs out of memory if batch_size is 1200.
# If you reduce the batch size to something that fits in memory,
# then the loss printed here should match the loss obtained in the for loop below 
# loss_fn1 = losses.NTXentLoss()
# loss = loss_fn1(a, b)
# print(loss)


# doesn't run out of memory
loss_fn2 = losses.NTXentLoss(reducer=reducers.DoNothingReducer())
# Do the following for each of your 1200-sized batches
loss = 0
sub_batch_size = 32
e = sub_batch_size
all_losses = []
for s in range(0, batch_size, sub_batch_size):
    # get current anchors
    curr_anchors = a[s:e]
    curr_anchor_labels = b[s:e]

    # manually get all pairs because we need to remove self-comparisons
    all_pairs = lmu.get_all_pairs_indices(curr_anchor_labels, b)
    all_pairs = lmu.remove_self_comparisons(all_pairs, torch.arange(s,e, device=device), len(b))

    # compute loss
    curr_loss = loss_fn2(curr_anchors, indices_tuple=all_pairs, ref_emb=a)
    all_losses.append(curr_loss["loss"]["losses"])
    s = e
    e += sub_batch_size

all_losses = torch.cat(all_losses, dim=0)
loss = torch.mean(all_losses)
print(loss)
```

Here's a google colab notebook containing the above code: https://colab.research.google.com/drive/1jxY4giSdTo3kkgagSn7kzmvJ0AGayh7y?usp=sharing

**Comment by siddagra** [comment]
Thanks a lot for all the help!! You are amazing!

I had a few questions:

- What are the arguments of `loss_fn2` (NT-Xent loss computation)  and how should they be formatted. I still don't quite understand this as the documentation did not seem to contain this information. 
- Why is the memory usage so high in the first place (for 1200 embeddings)?
- Is it trying to create all possible 1200 choose 2 combinations when computing the loss?
- If I can provide/sample indices of positive and negative pairs, would it reduce memory usage? 
- Would it be beneficial to have equal number of positive and negative pairs or some other distribution is more suitable instead?

Please help me understand this better. Thanks.
